name: Bausystem
version: '1.0'
main: com.wargear.builderPlots.BuilderPlots
api-version: '1.21'
authors: [ dervarex,meowtroid24,antonstiko ]
description: mlt builderplots
website: cattech-3d.w3spaces.com
